"""Generate a self-contained agent/my_agent.py for the Kaggle submission.

The official ARC-AGI-3 starter ships ONLY the single file agent/my_agent.py into
the notebook (scripts/build_notebook.py splices its text verbatim). Our agent is
a multi-module package under agent/, so to submit it AS-IS we embed the whole
package inside that one file.

This script zips every module of the agent/ package (except my_agent.py itself
and __pycache__), base64-encodes the archive, and writes agent/my_agent.py as a
self-extracting shim that, on import:

  1. unpacks the embedded package into a temp dir and puts it on sys.path, then
  2. imports our framework agent (OurSearchAgent) and exposes it as ``MyAgent`` --
     the class name the ARC-AGI-3-Agents registry imports.

Run this BEFORE scripts/build_notebook.py. It is idempotent: each run rebuilds
my_agent.py from the current agent/ sources.

    python scripts/bundle_agent.py
"""
from __future__ import annotations

import base64
import io
import textwrap
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "agent"
OUT = PKG / "my_agent.py"

# Embed source plus the data assets the package loads package-relatively:
#   .py    — the agent modules
#   .json  — settings JSON + the move-proposer schemas
#            (agent/assets/prompts/{input-observation,output-action}-schema.json,
#            loaded by core/llm_prompt.py at runtime).
#   .tsv   — the v14 asset catalogs (agent/assets/*.tsv: words, relations, roles,
#            goal_patterns, goal_kinds, solvers) that AssetLoader reads at init.
#            Without these the agent cannot construct (even the classical path),
#            so they MUST be bundled.
#   .md    — the move-proposer prompt template
#            (agent/assets/prompts/prompt-template.md, loaded by
#            core/llm_prompt.load_prompt() at runtime). Without it the LLM
#            proposer cannot construct and declines. The ONLY .md under agent/
#            is this template (verified), so the bare suffix is safe; this
#            mirrors the proven practice builder (build_practice_kernel.py).
_INCLUDE_SUFFIXES = {".py", ".json", ".tsv", ".md"}


def _bundled_files() -> list[Path]:
    files: list[Path] = []
    for p in sorted(PKG.rglob("*")):
        if not p.is_file():
            continue
        if p.name == OUT.name:  # never embed my_agent.py inside itself
            continue
        if "__pycache__" in p.parts:
            continue
        if p.suffix not in _INCLUDE_SUFFIXES:
            continue
        files.append(p)
    return files


def _build_zip(files: list[Path]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in files:
            arcname = "agent/" + p.relative_to(PKG).as_posix()  # keep package layout
            zf.write(p, arcname)
    return buf.getvalue()


# NOTE: the generated file embeds the base64 inside a triple-quoted string; the
# embedded newlines are ignored by base64.b64decode (validate=False default).
_TEMPLATE = '''\
"""ARC-AGI-3 competition agent -- self-contained entry point.

AUTO-GENERATED by scripts/bundle_agent.py -- DO NOT EDIT BY HAND.
To change the agent, edit the agent/ package (a derived export of the private
dev repo) and re-run:  python scripts/bundle_agent.py

The official notebook mechanism ships only this single file, so it carries the
whole agent/ package as an embedded zip. On import it unpacks the package onto
sys.path and exposes our framework agent as ``MyAgent`` (the name the
ARC-AGI-3-Agents registry expects).
"""
from __future__ import annotations

import base64
import io
import os
import sys
import tempfile
import zipfile

# base64 of a zip of the agent/ package (newlines ignored by b64decode).
_BUNDLE_B64 = """
{b64}
"""

_BUNDLE_DIR = os.path.join(tempfile.gettempdir(), "gr_arc_agent_bundle")


def _ensure_bundle() -> None:
    """Unpack the embedded agent/ package once and put it on sys.path."""
    marker = os.path.join(_BUNDLE_DIR, "agent", "__init__.py")
    if not os.path.exists(marker):
        data = base64.b64decode(_BUNDLE_B64)
        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            zf.extractall(_BUNDLE_DIR)
    if _BUNDLE_DIR not in sys.path:
        sys.path.insert(0, _BUNDLE_DIR)


_ensure_bundle()

from agent.search_agent import OurSearchAgent  # noqa: E402  (resolved from the bundle)


class MyAgent(OurSearchAgent):
    """Competition entry: our search-based agent, shipped as-is."""

    pass
'''


def main() -> None:
    files = _bundled_files()
    archive = _build_zip(files)
    b64 = base64.b64encode(archive).decode("ascii")
    b64_wrapped = "\n".join(textwrap.wrap(b64, 116))
    OUT.write_text(_TEMPLATE.format(b64=b64_wrapped), encoding="utf-8")
    print(
        f"[bundle_agent] wrote {OUT.relative_to(ROOT).as_posix()} "
        f"({len(files)} files, zip {len(archive)} B, b64 {len(b64)} chars)"
    )


if __name__ == "__main__":
    main()
